name: Nix flake check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - run: nix flake check
